use super::Strings;

pub(super) const UPDATE_VIA_WINGET_LABEL: &str = "通过 WinGet 更新";

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex 用量任务栏",
    refresh: "刷新",
    update_frequency: "刷新频率",
    one_minute: "1 分钟",
    five_minutes: "5 分钟",
    fifteen_minutes: "15 分钟",
    one_hour: "1 小时",
    models: "模型",
    claude_code_model: "Claude Code",
    codex_model: "Codex",
    antigravity_model: "Antigravity",
    settings: "设置",
    start_with_windows: "开机启动",
    reset_position: "重置位置",
    language: "语言",
    system_default: "跟随系统",
    check_for_updates: "检查更新",
    checking_for_updates: "正在检查更新...",
    updates: "更新",
    update_in_progress: "已经在检查更新。",
    up_to_date: "你已经在使用最新版本。",
    up_to_date_short: "已是最新",
    update_failed: "无法自动更新",
    applying_update: "正在应用更新...",
    update_to: "更新到",
    update_available: "有可用更新",
    update_prompt_now: "版本 {version} 已可用。是否现在更新？",
    exit: "退出",
    show_widget: "显示小组件",
    session_window: "5h",
    weekly_window: "7d",
    now: "现在",
    day_suffix: "天",
    hour_suffix: "小时",
    minute_suffix: "分",
    second_suffix: "秒",
    token_expired_title: "Claude Code 认证错误",
    token_expired_body:
        "请在终端中运行 'claude'，然后使用 '/login' 并按提示操作。完成后刷新或重启本应用。",
    codex_token_expired_title: "Codex 认证错误",
    codex_token_expired_body: "请在终端中运行 'codex' 并按登录提示操作。完成后刷新或重启本应用。",
    antigravity_token_expired_title: "Antigravity 认证错误",
    antigravity_token_expired_body: "请打开 Antigravity 并重新登录。完成后刷新或重启本应用。",
    codex_window_title: "Codex 用量任务栏",
    antigravity_window_title: "Antigravity 用量监控",
};
